export const LISTING_STATUS = {
  DRAFT: 'draft',
  PENDING_REVIEW: 'pending-review',
  VERIFIED: 'verified',
  REJECTED: 'rejected',
};

export const WORKFLOW_STATUS = {
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  COMPLETED: 'completed',
  FLAGGED: 'flagged',
};

export const users = [
  {
    id: 'user_tenant_1',
    clerkId: 'seed_tenant',
    role: 'tenant',
    name: 'Ada Tenant',
    email: 'ada@example.com',
    phone: '+2348001234567',
    onboardingComplete: true,
    verificationStatus: 'verified',
  },
  {
    id: 'user_landlord_1',
    clerkId: 'seed_landlord',
    role: 'landlord',
    name: 'Kemi Landlord',
    email: 'kemi@example.com',
    phone: '+2348002222222',
    onboardingComplete: true,
    verificationStatus: 'verified',
    bank: {
      bankName: 'GTBank',
      accountName: 'Kemi Properties Ltd',
      accountNumberLast4: '1290',
    },
  },
  {
    id: 'user_agent_1',
    clerkId: 'seed_agent',
    role: 'agent',
    name: 'Michael Agent',
    email: 'michael@example.com',
    phone: '+2348003333333',
    onboardingComplete: true,
    verificationStatus: 'verified',
    serviceAreas: ['Lekki', 'Yaba', 'Akoka'],
  },
  {
    id: 'user_inspector_1',
    clerkId: 'seed_inspector',
    role: 'inspector',
    name: 'Chika Inspector',
    email: 'chika@example.com',
    phone: '+2348004444444',
    onboardingComplete: true,
    verificationStatus: 'verified',
    serviceAreas: ['Lagos Mainland', 'Lagos Island'],
  },
];

export const properties = [
  {
    id: '1',
    type: 'rental',
    segment: 'general',
    name: 'Luxury 2-Bed Apartment',
    location: 'Lekki Phase 1, Lagos',
    area: 'lagos_island',
    price: 3500000,
    image: 'https://images.unsplash.com/photo-1592494804071-faea15d93a8a',
    amenities: ['power', 'security', 'parking', 'water'],
    roomType: '2bed',
    tag: 'Premium',
    landlordId: 'user_landlord_1',
    agentId: 'user_agent_1',
    inspectorId: 'user_inspector_1',
    status: LISTING_STATUS.VERIFIED,
    availableFrom: '2026-08-01',
    verificationNotes: 'Address, photos, utilities, and ownership documents verified.',
  },
  {
    id: '2',
    type: 'rental',
    segment: 'student',
    name: 'Royal Heights Hostel',
    location: 'Akoka, Lagos',
    area: 'lagos_mainland',
    university: 'unilag',
    price: 150000,
    image: 'https://images.unsplash.com/photo-1683229284577-4e697f2cbe19',
    amenities: ['wifi', 'power', 'security'],
    roomType: 'self-contain',
    tag: '5 mins to campus',
    landlordId: 'user_landlord_1',
    agentId: 'user_agent_1',
    inspectorId: 'user_inspector_1',
    status: LISTING_STATUS.VERIFIED,
    availableFrom: '2026-07-20',
    verificationNotes: 'Student proximity and safety checks completed.',
  },
  {
    id: '3',
    type: 'rental',
    segment: 'general',
    name: 'Cozy Studio Flat',
    location: 'Yaba, Lagos',
    area: 'lagos_mainland',
    price: 800000,
    image: 'https://images.unsplash.com/photo-1658040713006-926bad583a73',
    amenities: ['power', 'water'],
    roomType: 'self-contain',
    tag: 'Newly Renovated',
    landlordId: 'user_landlord_1',
    agentId: 'user_agent_1',
    inspectorId: 'user_inspector_1',
    status: LISTING_STATUS.PENDING_REVIEW,
    availableFrom: '2026-07-18',
    verificationNotes: 'Awaiting final water and power evidence.',
  },
  {
    id: '4',
    type: 'rental',
    segment: 'student',
    name: "Scholar's Lodge",
    location: 'Bodija, Ibadan',
    area: 'ibadan',
    university: 'ui',
    price: 95000,
    image: 'https://images.unsplash.com/photo-1629079447838-3d78840ee8cf',
    amenities: ['wifi', 'security', 'water'],
    roomType: 'single',
    tag: 'Quiet Environment',
    landlordId: 'user_landlord_1',
    status: LISTING_STATUS.VERIFIED,
    availableFrom: '2026-09-01',
    verificationNotes: 'Verified for student rental standards.',
  },
];

export const hostels = [
  {
    id: '1',
    name: 'Royal Heights',
    location: 'Akoka, Lagos',
    university: 'unilag',
    price: 120000,
    image: 'https://images.unsplash.com/photo-1683229284577-4e697f2cbe19',
    amenities: ['wifi', 'power', 'security'],
    roomType: 'self-contain',
    distance: '5 mins walk',
    landlordId: 'user_landlord_1',
    agentId: 'user_agent_1',
    inspectorId: 'user_inspector_1',
    status: LISTING_STATUS.VERIFIED,
  },
  {
    id: '2',
    name: "Scholar's Lodge",
    location: 'Bodija, Ibadan',
    university: 'ui',
    price: 95000,
    image: 'https://images.unsplash.com/photo-1680210851458-b7dc5685e06e',
    amenities: ['wifi', 'security', 'water'],
    roomType: 'shared',
    distance: '10 mins walk',
    landlordId: 'user_landlord_1',
    status: LISTING_STATUS.VERIFIED,
  },
  {
    id: '3',
    name: 'Campus View Apartments',
    location: 'Ile-Ife, Osun',
    university: 'oau',
    price: 85000,
    image: 'https://images.unsplash.com/photo-1657639754502-3c138cb24b4c',
    amenities: ['wifi', 'power', 'parking'],
    roomType: 'apartment',
    distance: '3 mins walk',
    landlordId: 'user_landlord_1',
    status: LISTING_STATUS.VERIFIED,
  },
  {
    id: '4',
    name: 'Elite Residence',
    location: 'Yaba, Lagos',
    university: 'unilag',
    price: 150000,
    image: 'https://images.unsplash.com/photo-1658040713006-926bad583a73',
    amenities: ['wifi', 'power', 'security', 'kitchen'],
    roomType: 'single',
    distance: '8 mins walk',
    landlordId: 'user_landlord_1',
    status: LISTING_STATUS.VERIFIED,
  },
  {
    id: '5',
    name: 'Student Haven',
    location: 'Nsukka, Enugu',
    university: 'unn',
    price: 75000,
    image: 'https://images.unsplash.com/photo-1531904300735-5f40721f712f',
    amenities: ['wifi', 'water', 'security'],
    roomType: 'shared',
    distance: '12 mins walk',
    landlordId: 'user_landlord_1',
    status: LISTING_STATUS.VERIFIED,
  },
];

export const inspections = [
  {
    id: 'inspection_1',
    listingId: '1',
    tenantId: 'user_tenant_1',
    agentId: 'user_agent_1',
    inspectorId: 'user_inspector_1',
    scheduledFor: '2026-07-08T10:00:00+01:00',
    status: WORKFLOW_STATUS.CONFIRMED,
    notes: 'Tenant requested morning viewing.',
  },
  {
    id: 'inspection_2',
    listingId: '2',
    tenantId: 'user_tenant_1',
    agentId: 'user_agent_1',
    inspectorId: 'user_inspector_1',
    scheduledFor: '2026-07-09T13:30:00+01:00',
    status: WORKFLOW_STATUS.PENDING,
    notes: 'Awaiting landlord confirmation.',
  },
];

export const reservations = [
  {
    id: 'reservation_1',
    listingId: '1',
    tenantId: 'user_tenant_1',
    amount: 350000,
    status: WORKFLOW_STATUS.PENDING,
    paymentStatus: 'awaiting-payment',
    createdAt: '2026-07-04T09:00:00+01:00',
  },
];

export const maintenanceRequests = [
  {
    id: 'maintenance_1',
    listingId: '1',
    tenantId: 'user_tenant_1',
    title: 'Kitchen sink leak',
    priority: 'medium',
    status: WORKFLOW_STATUS.PENDING,
    createdAt: '2026-07-03T15:45:00+01:00',
  },
];

export const messages = [
  {
    id: 'message_1',
    threadId: 'thread_1',
    fromUserId: 'user_tenant_1',
    toUserId: 'user_landlord_1',
    subject: 'Inspection availability',
    body: 'Can I inspect the Lekki apartment on Wednesday morning?',
    read: false,
    createdAt: '2026-07-04T08:20:00+01:00',
  },
];

